# Desafio 011

Você tem a tabela de Atendimentos com a duração das consultas e o agravo, mas os nomes das doenças estão bagunçados. E você tem a tabela de Pacientes com as idades. Você precisa limpar, cruzar, calcular e extrair a estatística descritiva.

### O Código Inicial:

In [8]:
import pandas as pd

# Tabela 1: Registros de Atendimentos do Consultório
dados_atendimentos = {
    'ID_Atendimento': [1001, 1002, 1003, 1004, 1005, 1006],
    'ID_Paciente': [1, 2, 3, 4, 5, 6],
    'Agravo': [' dengue ', 'gripe', 'DENGUE', ' gripe ', 'Hipertensão', 'hipertensão'],
    'Tempo_Minutos': [25, 15, 30, 20, 45, 40]
}
df_atendimentos = pd.DataFrame(dados_atendimentos)

# Tabela 2: Cadastro de Pacientes (Idades)
dados_pacientes = {
    'ID_Paciente': [1, 2, 3, 4, 5, 6],
    'Nome': ['Carlos', 'Ana', 'Seu Antenor', 'Julia', 'Marcos', 'Eva'],
    'Idade': [24, 28, 88, 26, 52, 54]
}
df_pacientes = pd.DataFrame(dados_pacientes)

display(df_atendimentos)
display(df_pacientes)

   ID_Atendimento  ID_Paciente       Agravo  Tempo_Minutos
0            1001            1      dengue              25
1            1002            2        gripe             15
2            1003            3       DENGUE             30
3            1004            4       gripe              20
4            1005            5  Hipertensão             45
5            1006            6  hipertensão             40

   ID_Paciente         Nome  Idade
0            1       Carlos     24
1            2          Ana     28
2            3  Seu Antenor     88
3            4        Julia     26
4            5       Marcos     52
5            6          Eva     54

### Suas Tarefas:

1. **Limpeza de Strings**: Na tabela de atendimentos, os textos da coluna 'Agravo' vieram com espaços e letras misturadas. Padronize a coluna deixando tudo em Maiúsculo e sem espaços nas pontas usando .str.strip().str.upper().

In [9]:
df_atendimentos["Agravo"] = df_atendimentos["Agravo"].str.strip().str.upper()
display(df_atendimentos["Agravo"])

0         DENGUE
1          GRIPE
2         DENGUE
3          GRIPE
4    HIPERTENSÃO
5    HIPERTENSÃO
Name: Agravo, dtype: str

2. **O Cruzamento Perfeito**: Faça um merge (INNER JOIN) entre a tabela de atendimentos e a tabela de pacientes usando a coluna em comum (ID_Paciente). Salve no df_consolidado.

In [10]:
df_consolidado = pd.merge(
    df_pacientes,
    df_atendimentos,
    on="ID_Paciente",
    how="inner"
)
display(df_consolidado)

   ID_Paciente         Nome  Idade  ID_Atendimento       Agravo  Tempo_Minutos
0            1       Carlos     24            1001       DENGUE             25
1            2          Ana     28            1002        GRIPE             15
2            3  Seu Antenor     88            1003       DENGUE             30
3            4        Julia     26            1004        GRIPE             20
4            5       Marcos     52            1005  HIPERTENSÃO             45
5            6          Eva     54            1006  HIPERTENSÃO             40

3. **Análise Estatística Descritiva**: Utilizando o seu df_consolidado, agrupe os dados por Agravo e, para a coluna Idade, calcule de uma só vez: a Média, a Mediana e o Desvio Padrão.

   - Dica de ouro: O Pandas tem um comando fantástico chamado .agg() que permite aplicar várias funções de uma vez após o groupby.

   - Sintaxe: `df.groupby('Coluna_Grupo')['Coluna_Alvo'].agg(['mean', 'median', 'std'])`

In [15]:
display(df_consolidado.groupby("Agravo")["Idade"].agg(["mean", "median", "std"]))

             mean  median        std
Agravo
DENGUE       56.0    56.0  45.254834
GRIPE        27.0    27.0   1.414214
HIPERTENSÃO  53.0    53.0   1.414214

4. **Interpretação do Analista**: Olhando para o resultado do seu código, printe uma resposta em texto respondendo: Qual agravo possui a maior diferença entre a Média e a Mediana (o que indica a presença de um paciente com idade muito fora do padrão/outlier)?

In [16]:
print("O Agravo com maior diferença de idade é: Dengue")

O Agravo com maior diferença de idade é: Dengue