# Desafio 005

Você recebeu dois relatórios separados do sistema da empresa. O primeiro relatório contém as Vendas do mês, mas possui apenas o ID_Cliente. O segundo relatório é o Cadastro de Clientes, que liga o ID_Cliente ao Nome e à Região dele.

Seu objetivo é cruzar essas duas tabelas para gerar um relatório unificado e responder a algumas perguntas da diretoria.

### Seu código inicial:

In [1]:
import pandas as pd

# Tabela A: Movimentação de Vendas
dados_vendas = {
    'ID_Cliente': [101, 102, 101, 103, 102, 104],
    'Produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Notebook', 'Teclado'],
    'Preço': [4000.00, 150.00, 250.00, 1200.00, 4000.00, 250.00],
    'Quantidade': [1, 2, 3, 1, 1, 5]
}
df_vendas = pd.DataFrame(dados_vendas)

# Tabela B: Cadastro de Clientes
dados_cadastro = {
    'ID_Cliente': [101, 102, 103, 104],
    'Nome_Cliente': ['Alexandre', 'Vivian', 'Estevão', 'Ester'],
    'Região': ['Sul', 'Sul', 'Sudeste', 'Nordeste']
}
df_cadastro = pd.DataFrame(dados_cadastro)

print("Tabela de vendas:")
display(df_vendas)
print("Tabela de Cadastro:")
display(df_cadastro)

Tabela de vendas:

   ID_Cliente   Produto   Preço  Quantidade
0         101  Notebook  4000.0           1
1         102     Mouse   150.0           2
2         101   Teclado   250.0           3
3         103   Monitor  1200.0           1
4         102  Notebook  4000.0           1
5         104   Teclado   250.0           5

Tabela de Cadastro:

   ID_Cliente Nome_Cliente    Região
0         101    Alexandre       Sul
1         102       Vivian       Sul
2         103      Estevão   Sudeste
3         104        Ester  Nordeste

### Suas tarefas:

1. **O Cruzamento**: Junte os dois DataFrames em um único chamado df_final usando como base a coluna em comum.

In [2]:
df_final = pd.merge(df_vendas, df_cadastro, on="ID_Cliente", how="inner")
display(df_final)

   ID_Cliente   Produto   Preço  Quantidade Nome_Cliente    Região
0         101  Notebook  4000.0           1    Alexandre       Sul
1         102     Mouse   150.0           2       Vivian       Sul
2         101   Teclado   250.0           3    Alexandre       Sul
3         103   Monitor  1200.0           1      Estevão   Sudeste
4         102  Notebook  4000.0           1       Vivian       Sul
5         104   Teclado   250.0           5        Ester  Nordeste

2. **Faturamento por Produto**: Utilizando o df_final, calcule e mostre na tela o Faturamento Total de cada produto. Adicione essa informação como uma nova coluna chamada 'Faturamento'.

In [3]:
df_final["Faturamento"] = df_final["Preço"] * df_final["Quantidade"]
display(df_final)

,ID_Cliente,Produto,Preço,Quantidade,Nome_Cliente,Região,Faturamento
0,101,Notebook,4000.0,1,Alexandre,Sul,4000.0
1,102,Mouse,150.0,2,Vivian,Sul,300.0
2,101,Teclado,250.0,3,Alexandre,Sul,750.0
3,103,Monitor,1200.0,1,Estevão,Sudeste,1200.0
4,102,Notebook,4000.0,1,Vivian,Sul,4000.0
5,104,Teclado,250.0,5,Ester,Nordeste,1250.0

3. **Análise Regional**: Descubra qual Região gerou o maior faturamento total para a empresa. Agrupe os dados por 'Região' e some o 'Faturamento'.

In [4]:
display(df_final.groupby('Região')['Faturamento'].sum())

Região
Nordeste    1250.0
Sudeste     1200.0
Sul         9050.0
Name: Faturamento, dtype: float64

4. **Filtro de Elite**: Exiba uma tabela contendo apenas as vendas onde o faturamento por linha foi maior que R$ 1.000,00.

In [5]:
display(df_final[df_final['Faturamento'] > 1000])

,ID_Cliente,Produto,Preço,Quantidade,Nome_Cliente,Região,Faturamento
0,101,Notebook,4000.0,1,Alexandre,Sul,4000.0
3,103,Monitor,1200.0,1,Estevão,Sudeste,1200.0
4,102,Notebook,4000.0,1,Vivian,Sul,4000.0
5,104,Teclado,250.0,5,Ester,Nordeste,1250.0