# Desafio 004

Você recebeu uma planilha de cadastro de clientes de uma plataforma online. Porém, a tabela está cheia de informações faltando (None ou NaN). O seu chefe quer que você limpe esses dados seguindo regras de negócio específicas e, no final, salve o resultado limpo em um arquivo CSV.

### Seu código inicial

In [2]:
import pandas as pd
import numpy as np

# Dados brutos enviados pelo sistema
dados_clientes = {
    'Nome': ['Alexandre', 'Vivian', None, 'Estevão', 'Ester', None],
    'Idade': [28, 26, 35, np.nan, 12, 44],
    'E-mail': ['alexandre@email.com', None, 'compras@email.com', 'estevao@email.com', 'ester@email.com', None],
    'Cidade': ['Paraná', 'Paraná', 'São Paulo', 'Paraná', 'Minas Gerais', 'Bahia']
}

df = pd.DataFrame(dados_clientes)
display(df)

        Nome  Idade               E-mail        Cidade
0  Alexandre   28.0  alexandre@email.com        Paraná
1     Vivian   26.0                  NaN        Paraná
2        NaN   35.0    compras@email.com     São Paulo
3    Estevão    NaN    estevao@email.com        Paraná
4      Ester   12.0      ester@email.com  Minas Gerais
5        NaN   44.0                  NaN         Bahia

### Suas tarefas:


1. **Identificar o problema**: Mostre na tela quantos dados nulos/faltantes existem em cada coluna da tabela.

In [8]:
display(df.isnull().sum())

Nome      0
Idade     1
E-mail    2
Cidade    0
dtype: int64

2. **Tratar os nomes**: Quem não preencheu o nome deve receber o texto "Não Informado".

In [7]:
df["Nome"] = df["Nome"].fillna("Não Informado")
display(df['Nome'])

0        Alexandre
1           Vivian
2    Não Informado
3          Estevão
4            Ester
5    Não Informado
Name: Nome, dtype: str

3. **Tratar as idades**: Quem não preencheu a idade deve receber a média de idade dos outros clientes da tabela.

In [9]:
df["Idade"] = df["Idade"].fillna(int(df["Idade"].mean()))
display(df['Idade'])

0    28.0
1    26.0
2    35.0
3    29.0
4    12.0
5    44.0
Name: Idade, dtype: float64

4. **Remover Linhas Críticas**: Clientes que não informaram o E-mail não servem para a campanha de marketing. Delete as linhas onde o e-mail esteja nulo.

In [11]:
df.dropna(subset=["E-mail"], inplace=True)
print("DataFrame final, limpo e corrigido:")
display(df)

DataFrame final, limpo e corrigido:

            Nome  Idade               E-mail        Cidade
0      Alexandre   28.0  alexandre@email.com        Paraná
2  Não Informado   35.0    compras@email.com     São Paulo
3        Estevão   29.0    estevao@email.com        Paraná
4          Ester   12.0      ester@email.com  Minas Gerais

5. **Exportar**: Salve o seu DataFrame final, totalmente limpo e corrigido, em um arquivo chamado clientes_limpos.csv.

In [12]:
df.to_csv("clientes_limpos.csv", index=False)
print("Dataframe salvo em 'clientes_limpos.csv'")

Dataframe salvo em 'clientes_limpos.csv'