# Desafio 001

Imagine que você recebeu um relatório bruto de vendas de uma pequena loja de eletrônicos em formato de dicionário Python. O seu chefe quer que você use o **Pandas** para organizar esses dados e extrair algumas informações cruciais.
​
### Seu código inicial:

In [2]:
import pandas as pd

dados_loja = {
    'Produto': ['Teclado Mecânico', 'Mouse Wireless', 'Monitor 24"', 'Headset RGB'],
    'Preço': [250.00, 120.00, 899.90, 310.00],
    'Estoque': [15, 30, 7, 12]
}
df = pd.DataFrame(dados_loja)

### Suas tarefas:

1. Mostre a tabela completa na tela de forma organizada.

In [27]:
display(df)

            Produto  Preço  Estoque
0  Teclado Mecânico  250.0       15
1    Mouse Wireless  120.0       30
2       Monitor 24"  899.9        7
3       Headset RGB  310.0       12

2. Exiba apenas as 2 primeiras linhas do DataFrame para uma checagem rápida.

In [28]:
df.head(2)

            Produto  Preço  Estoque
0  Teclado Mecânico  250.0       15
1    Mouse Wireless  120.0       30

3. Mostre a estrutura dos dados (quantas linhas, colunas e os tipos de dados que estão ali dentro).

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Produto  4 non-null      str
 1   Preço    4 non-null      float64
 2   Estoque  4 non-null      int64
dtypes: float64(1), int64(1), str(1)
memory usage: 228.0 bytes

4. Adicione uma nova linha no final com o produto "Gabinete Gamer" que custa 450.00 e tem 8 unidades no estoque.

In [30]:
df = pd.concat(
    [
        df,
        pd.DataFrame(
            {
                "Produto": ["Gabinete Gamer"],
                "Preço": [450],
                "Estoque": [8]
            }
        )
    ],
    ignore_index=True
)
display(df)

            Produto  Preço  Estoque
0  Teclado Mecânico  250.0       15
1    Mouse Wireless  120.0       30
2       Monitor 24"  899.9        7
3       Headset RGB  310.0       12
4    Gabinete Gamer  450.0        8

5. Calcule e mostre na tela o valor total do estoque da loja.

In [3]:
print(f"R${(df["Preço"] * df["Estoque"]).sum():.2f}")

R$17369.30