# Desafio 003

Sua missão neste desafio é pegar a nossa mesma tabela de informática e resolver 3 problemas práticos de alteração e resumo de dados.

---

### Seu código inicial:

In [6]:
import pandas as pd

dados_informatica = {
    'Produto': ['Notebook Dell', 'Teclado Mecânico', 'Monitor LG 29"', 'Mouse Gamer', 'Impressora HP', 'SSD 1TB'],
    'Categoria': ['Notebooks', 'Periféricos', 'Monitores', 'Periféricos', 'Printers', 'Armazenamento'],
    'Preço': [4200.00, 250.00, 1350.00, 180.00, 890.00, 410.00],
    'Estoque': [5, 15, 4, 22, 3, 18]
}

df = pd.DataFrame(dados_informatica)
display(df)

            Produto      Categoria   Preço  Estoque
0     Notebook Dell      Notebooks  4200.0        5
1  Teclado Mecânico    Periféricos   250.0       15
2    Monitor LG 29"      Monitores  1350.0        4
3       Mouse Gamer    Periféricos   180.0       22
4     Impressora HP       Printers   890.0        3
5           SSD 1TB  Armazenamento   410.0       18

### Suas tarefas:

1. **Correção de Dados**: O estagiário cadastrou a categoria da Impressora HP como 'Printers' (em inglês). Modifique esse valor específico para ficar em português: 'Periféricos'.

In [7]:
print(f"A categoria da linha 4 era '{df.loc[4, 'Categoria']}' e foi modificada para ", end="")
df.loc[4, "Categoria"] = "Periféricos"
print(f"'{df.loc[4, "Categoria"]}'")

A categoria da linha 4 era 'Printers' e foi modificada para 'Periféricos'

2. **A Inflação Chegou** (Operação em Massa): Devido às taxas de importação, todos os produtos da loja sofreram um aumento de 10% no preço. Atualize a coluna 'Preço' refletindo esse novo valor para todos os produtos de uma só vez.

In [8]:
print("Os preços eram:")
display(df[['Produto', 'Preço']])
df["Preço"] = df["Preço"] * 1.1
print("Receberam 10% de aumento e foram para:")
display(df[["Produto", "Preço"]])

Os preços eram:

            Produto   Preço
0     Notebook Dell  4200.0
1  Teclado Mecânico   250.0
2    Monitor LG 29"  1350.0
3       Mouse Gamer   180.0
4     Impressora HP   890.0
5           SSD 1TB   410.0

Receberam 10% de aumento e foram para:

            Produto   Preço
0     Notebook Dell  4620.0
1  Teclado Mecânico   275.0
2    Monitor LG 29"  1485.0
3       Mouse Gamer   198.0
4     Impressora HP   979.0
5           SSD 1TB   451.0

3. **Resumo por Categoria**: O gerente quer saber quantos produtos a loja tem no estoque total somando por cada Categoria. Agrupe os dados e mostre essa soma.

In [10]:
display(df.groupby('Categoria')['Estoque'].sum())

Categoria
Armazenamento    18
Monitores         4
Notebooks         5
Periféricos      40
Name: Estoque, dtype: int64