# Desafio 009

Imagine que você coletou dados novos de visitas de campo em um arquivo local ou dicionário. Sua missão é usar o Pandas para estruturar esses novos dados e inseri-los de uma vez só em uma nova tabela dentro do nosso banco de dados. Depois, para garantir que funcionou, você fará uma consulta SQL básica para ler o que foi salvo.

### Seu código inicial:

In [14]:
import pandas as pd
import sqlite3

conexao = sqlite3.connect(':memory:')

dados = {
    'Paciente': ['Seu Joaquim', 'Dona Ivone', 'Beatriz Cruz'],
    'Idade': [74, 61, 23],
    'Agravo': ['Diabetes', 'Hipertensão', 'Exame Rotina'],
    'Tempo_Minutos': [35, 20, 15]
}

### Suas tarefas:

1. **Criar o DataFrame Novo**: Monte o DataFrame com os novos dados de visitas que estão no código inicial abaixo.

In [15]:
df = pd.DataFrame(dados)
display(df)

       Paciente  Idade        Agravo  Tempo_Minutos
0   Seu Joaquim     74      Diabetes             35
1    Dona Ivone     61   Hipertensão             20
2  Beatriz Cruz     23  Exame Rotina             15

2. **Gravar no Banco**:Salve esse DataFrame em uma tabela chamada novas_visitas.

In [18]:
df.to_sql(
    "novas_visitas",
    conexao,
    if_exists="replace",
    index=False
)

3

3. **A Prova Real**: Para testar se o banco realmente recebeu os dados, faça um pd.read_sql_query("SELECT * FROM novas_visitas", conexao) e exiba o resultado na tela.

In [19]:
df2 = pd.read_sql_query(
    "SELECT * FROM novas_visitas",
    conexao
)
display(df2)

       Paciente  Idade        Agravo  Tempo_Minutos
0   Seu Joaquim     74      Diabetes             35
1    Dona Ivone     61   Hipertensão             20
2  Beatriz Cruz     23  Exame Rotina             15