# Desafio 002

Você recebeu uma tabela maior com o estoque de uma loja de informática. Seu objetivo é criar um programa em Python que carregue esses dados em um DataFrame e resolva 4 problemas de negócio usando filtros, ordenação e o acesso a linhas específicas que acabamos de aprender.

---

### Dados Iniciais para o seu código:

In [1]:
import pandas as pd

dados_informatica = {
    'Produto': ['Notebook Dell', 'Teclado Mecânico', 'Monitor LG 29"', 'Mouse Gamer', 'Impressora HP', 'SSD 1TB'],
    'Categoria': ['Notebooks', 'Periféricos', 'Monitores', 'Periféricos', 'Printers', 'Armazenamento'],
    'Preço': [4200.00, 250.00, 1350.00, 180.00, 890.00, 410.00],
    'Estoque': [5, 15, 4, 22, 3, 18]
}

df = pd.DataFrame(dados_informatica)

display(df)

            Produto      Categoria   Preço  Estoque
0     Notebook Dell      Notebooks  4200.0        5
1  Teclado Mecânico    Periféricos   250.0       15
2    Monitor LG 29"      Monitores  1350.0        4
3       Mouse Gamer    Periféricos   180.0       22
4     Impressora HP       Printers   890.0        3
5           SSD 1TB  Armazenamento   410.0       18

### Suas Tarefas:

1. **Filtro de Categoria**: Exiba na tela apenas os produtos que pertencem à categoria 'Periféricos'.

In [6]:
display(df[df["Categoria"] == "Periféricos"])

            Produto    Categoria  Preço  Estoque
1  Teclado Mecânico  Periféricos  250.0       15
3       Mouse Gamer  Periféricos  180.0       22

2. **Alerta de Estoque Baixo**: O gerente precisa saber quais produtos estão com menos de 5 unidades no estoque. Filtre e mostre apenas essas linhas.

In [7]:
display(df[df["Estoque"] < 5])

          Produto  Categoria   Preço  Estoque
2  Monitor LG 29"  Monitores  1350.0        4
4   Impressora HP   Printers   890.0        3

3. **Ordenação de Preços**: Mostre a tabela completa, mas ordenada do produto mais caro para o mais barato.

In [8]:
display(df.sort_values("Preço", ascending=False))

            Produto      Categoria   Preço  Estoque
0     Notebook Dell      Notebooks  4200.0        5
2    Monitor LG 29"      Monitores  1350.0        4
4     Impressora HP       Printers   890.0        3
5           SSD 1TB  Armazenamento   410.0       18
1  Teclado Mecânico    Periféricos   250.0       15
3       Mouse Gamer    Periféricos   180.0       22

4. **Consulta VIP** (Acesso Específico): Descubra e mostre na tela apenas o nome do produto e o preço que estão exatamente na linha de índice de posição 4.

In [9]:
display(df.loc[4, ["Produto", "Preço"]])

Produto    Impressora HP
Preço              890.0
Name: 4, dtype: object